project_id = "xtxxgjrkggnjdbjnjskm"

[functions.seed-demo-users]
verify_jwt = false

[functions.login-by-username]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.finance-summary]
verify_jwt = false
